version: '3.9'
services: 
  db:
    image: mysql:8.0.21
    container_name: TLBlitz-db
    ports:
      - 3002:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
networks:
    default:
        external:
            name: TLBlitz_NW