version: '3.9'
services:
  # frontend:
  #   container_name: TLBlitz_Front
  #   build: ./frontend
  #   depends_on:
  #     backend:
  #       condition: service_healthy
  #   ports:
  #     - 3000:3000
  #   restart: always
  #   healthcheck:
  #     test: ["CMD", "lsof", "-t", "-i:3000"]
  #     timeout: 10s
  #     retries: 5
  backend:
    container_name: TLBlitz_Back
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3001:3001
    environment:
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${MYSQL_ROOT_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - JWT_KEY=${JWT_KEY}
    links:
      - db
    restart: always
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.21
    container_name: TLBlitz_DB
    ports:
      - 3002:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE